# Author: Stephen Murphy
# Created: April 2012
# Description: Install a preference file for new users
# Equivalent to old CopyPrefs pkg for InstaDMG
include /usr/local/share/luggage/luggage.make

TITLE=prefs_symhotkeys
REVERSE_DOMAIN=au.edu.ifss
PACKAGE_VERSION=1.0.0
PFILE=com.apple.symbolichotkeys.plist
PAYLOAD=pack-user-template-plist-${PFILE}
