# Author: Stephen Murphy
# Created: March 2012
# Description: Package TextWrangler 4 free app for unattended install

include /usr/local/share/luggage/luggage.make

TITLE=TextWrangler-4-0-1_Install
PACKAGE_VERSION=1.0.0
REVERSE_DOMAIN=au.edu.ifss
PAYLOAD=unbz2-applications-TextWrangler.app