# Author: Stephen Murphy
# Created: May 2012
# Description: Payload free package to run a postflight script
#              Deletes everything related to iWork08

include /usr/local/share/luggage/luggage.make

TITLE=remove_iWork08
PACKAGE_VERSION=1.0.0
REVERSE_DOMAIN=au.edu.ifss
PAYLOAD=pack-script-postflight
