# Author: Stephen Murphy
# Created: March 2012
# Description: Package VideoSpec free app for unattended install

include /usr/local/share/luggage/luggage.make

TITLE=VideoSpec-0-9-6_Install
PACKAGE_VERSION=1.0.0
REVERSE_DOMAIN=au.edu.ifss
PAYLOAD=unbz2-applications-VideoSpec.app