# Author: Stephen Murphy
# Created: March 2012
# Description: Package VLC 2.0.0 for unattended install

include /usr/local/share/luggage/luggage.make

TITLE=VLC_2-0-0_Install
PACKAGE_VERSION=1.0
REVERSE_DOMAIN=au.edu.ifss
PAYLOAD=unbz2-applications-VLC.app