# Author: Stephen Murphy
# Created: April 2012
# Description: Package DropCopy 1.75 for unattended install

include /usr/local/share/luggage/luggage.make

TITLE=DropCopy_1-75_Install
PACKAGE_VERSION=1.0.0
REVERSE_DOMAIN=au.edu.ifss
PAYLOAD=unbz2-applications-DropCopy.app