# Author: Stephen Murphy
# Created: May 2012
# Description: Install launch agent plist for running setup AU scripts (if not set in base image)
#
# Note that scripts need to be installed first (scripts_IFSS_AU-x.pkg)

include /usr/local/share/luggage/luggage.make

TITLE=launchAgent_setupAU
REVERSE_DOMAIN=au.edu.ifss
PACKAGE_VERSION=1.0.0
PAYLOAD=pack-Library-LaunchAgents-au.edu.ifss.setupAU.plist
