# Author: Stephen Murphy
# Created: May 2012
# Description: Payload free package to run a postflight script
#              Cleanup files and folders left behind after standard MC 5.53 uninstall

include /usr/local/share/luggage/luggage.make

TITLE=clean_AvidMC_5_53
PACKAGE_VERSION=1.0.0
REVERSE_DOMAIN=au.edu.ifss
PAYLOAD=pack-script-postflight
