# Author: Stephen Murphy
# Created: May 2012
# Description: Payload free package to run a postflight script
#              Deletes beta/non-MAS version of 5DtoRGB

include /usr/local/share/luggage/luggage.make

TITLE=remove_old_5DtoRGB
PACKAGE_VERSION=1.0.0
REVERSE_DOMAIN=au.edu.ifss
PAYLOAD=pack-script-postflight
