#!/bin/sh

# (c) 2010 Walter Meyer SUNY Purchase College

#  This script, and subsequent package, should ONLY BE RUN ON THE VOLUME
#   TO WHICH THE COMPUTER IS BOOTED!  Using this script in InstaDMG will cause
#   issues (printer is installed on InstaDMG computer, not IMAGED computer!).

# Script to install and setup printers on a Mac OS X system in a "Munki-Friendly" way.
# Make sure to install the required drivers first!

# Modified for IFSS printer by Stephen Murphy March 2012

# Check to make sure we're ONLY installing to the boot volume
if [ "$3" != "/" ]; then
       exit 0
fi

# Variables. Edit these.
printername="DocuCentre-IV%203060%20%20%28b0%3A39%3Ac8%29"
location="Student Lounge"
gui_display_name="Student DocuCentre-IV 3060"
address="mdns://DocuCentre-IV%203060%20%20%28b0%3A39%3Ac8%29._printer._tcp.local."
driver_ppd="/Library/Printers/PPDs/Contents/Resources/FX Print Driver for Mac OS X.gz"

### Printer Install ###
# Install the printer.
/usr/sbin/lpadmin -p "$printername" -L "$location" -D "$gui_display_name" -v "$address" -P "$driver_ppd" -E -o printer-is-shared=false

# Enable and start the printers on the system (after adding the printer initially it is paused).
/usr/sbin/cupsenable $(lpstat -p | grep -w "printer" | awk '{print$2}')

# Set the printer as the default if we want.
/usr/bin/lpoptions -d $printername

### Other Installs ###
### Deleted by SM: saving printer configs and uninstaller ###

exit 0