# Author: Stephen Murphy
# Created: June 2012
# Description: Package HDFileConverterUpdater v1.3b1 for unattended install

include /usr/local/share/luggage/luggage.make

TITLE=HDFileConvUpd_13b1_Install
PACKAGE_VERSION=1.0
REVERSE_DOMAIN=au.edu.ifss
PAYLOAD=unbz2-applications-HDFileConverterUpdater.app