# Author: Stephen Murphy
# Created: May 2012
# Description: Payload free package to run a postflight script
#			   Delete/uninstall old Flash, AIR and kuler apps/files
#              Cleanup files and folders left behind after CS3 uninstall and Cleanup

include /usr/local/share/luggage/luggage.make

TITLE=clean_Adobe_CS3_FlAIRk
PACKAGE_VERSION=1.0.0
REVERSE_DOMAIN=au.edu.ifss
PAYLOAD=pack-script-postflight
