# Author: Stephen Murphy
# Created: May 2012
# Description: Install iWork preferences for new users (InstaDMG version)

include /usr/local/share/luggage/luggage.make

TITLE=prefs_iWork09_InstaDMG
REVERSE_DOMAIN=au.edu.ifss
PACKAGE_VERSION=1.0.0
PFILEK=com.apple.iWork.Keynote.plist
PFILEN=com.apple.iWork.Numbers.plist
PFILEP=com.apple.iWork.Pages.plist
PAYLOAD=\
	pack-user-template-plist-${PFILEK}\
	pack-user-template-plist-${PFILEN}\
	pack-user-template-plist-${PFILEP}




