#!/bin/bash
#

# Delete plist for existing users
# based on script from github.com/natewalck/LuggagePackages
# Changed for statement to just get username to handle paths better
# SM May 2012

PFILE=com.apple.quicktime.plugin.preferences.plist

for USERDIR in $( ls $3Users )
do
	if [ "${USERDIR}" != "Shared" ]
	then
		if [ -e "$3Users/$USERDIR/Library/Preferences/$PFILE" ]       # Check if plist file exists.
  		then
			sudo rm $3Users/$USERDIR/Library/Preferences/$PFILE
		fi
	fi
done

# Note - exit 0 will mean it exits successfully even if there are errors, and install will complete
#exit 0