# Author: Stephen Murphy
# Created: May 2012 :: July 2012 (InstaDMG version)
# Description: Install Flip4Mac preferences for new users (InstaDMG workflow)
# Disables update checking

include /usr/local/share/luggage/luggage.make
include ../common/userprefs.make

TITLE=prefs_Flip4Mac_InstaDMG
REVERSE_DOMAIN=au.edu.ifss
PACKAGE_VERSION=1.0.0
PFILE=net.telestream.wmv.plist
PAYLOAD=\
	pack-user-template-plist-${PFILE}



