# Author: Stephen Murphy
# Created: April 2012
# Description: Install a preference for new users (InstaDMG workflow)
# Very generic -- change PFILE as required

include /usr/local/share/luggage/luggage.make
include ../common/userprefs.make

TITLE=prefs_Lab2Dock_10_6_8
REVERSE_DOMAIN=au.edu.ifss
PACKAGE_VERSION=1.0.0
PFILE=com.apple.dock.plist
PAYLOAD=\
	pack-user-template-plist-${PFILE}
