#!/bin/bash

# Standard settings for images.
# Script is meant to be run as a postflight script in a .pkg file. 
# Also installs startup settings script as a Launchd item which is inside the package /Contents/Resources directory.
 
##### Begin Declare Variables Used by Script #####
 
# Declare 'defaults'and 'PlistBuddy'.
 
defaults="/usr/bin/defaults"
PlistBuddy="/usr/libexec/PlistBuddy"

# Determine the OS (to allow specific settings for 10.7)
# Note: not sure whether gets version of target image or of host OS
# But shouldn't matter, because have to build on the same (major) version

OS=`/usr/bin/sw_vers -productVersion | /usr/bin/cut -d "." -f 1,2`
 
# Declare directory variables.
 
PKG_DIR="$1/Contents/Resources"
SCRIPTS_DIR="$3/Library/Scripts/Purchase"
LAUNCHD_DIR="$3/Library/LaunchDaemons"
PRIVETC_DIR="$3/private/etc"
PREFS_DIR="$3/Library/Preferences"
USERPREFS_DIR="$3/System/Library/User Template/English.lproj/Library/Preferences"
ROOT="$3/"
# Set variable to location of update_dyld_shared_cache command on targetvolume.
UPDATE_DYLD="$3/usr/bin/update_dyld_shared_cache" 
 
##### End Declare Variables Used by Script #####
 
##### Begin Preference Setting #####
 
# These settings can be set on the target volume before startup.
 
#Enables SSH
#$PlistBuddy -c "Delete Disabled" $3/System/Library/LaunchDaemons/ssh.plist
 
# Display login window as Name and Password.
$defaults write "${PREFS_DIR}/com.apple.loginwindow" SHOWFULLNAME -bool YES

#Firewall Settings | 0 = Off | 1 = On For Specific Services | 2 = On For Essential Services
$defaults write "${PREFS_DIR}/com.apple.alf" globalstate -int 0

# Disable Time Machine Offers.
$defaults write "${PREFS_DIR}/com.apple.TimeMachine" DoNotOfferNewDisksForBackup -boolean true
 
# Disable Time Machine AutoBackup
$defaults write "${PREFS_DIR}/com.apple.TimeMachine" AutoBackup -boolean false

# Set desktop background to ifss standard pic (also done in image)
$defaults write "${USERPREFS_DIR}/com.apple.desktop" Background '{default = {ImageFilePath = "/Library/Desktop Pictures/IFSS_KeyImage_Sec_Logo.jpg"; };}'

# Set Safari Preferences.
$defaults write "${USERPREFS_DIR}/com.apple.Safari" HomePage http://www.ifss.edu.au/student-resources/
$defaults write "${USERPREFS_DIR}/com.apple.Safari" ShowStatusBar -boolean true
$defaults write "${USERPREFS_DIR}/com.apple.Safari" ConfirmClosingMultiplePages 0
$defaults write "${USERPREFS_DIR}/com.apple.Safari" AutoOpenSafeDownloads -boolean false

# Set QT Player 7 as default for mov, mp4 and avi files
$defaults write "${USERPREFS_DIR}/com.apple.LaunchServices" LSHandlers -array-add '{ LSHandlerContentType = "com.apple.quicktime-movie"; LSHandlerRoleAll = "com.apple.quicktimeplayer"; }'
$defaults write "${USERPREFS_DIR}/com.apple.LaunchServices" LSHandlers -array-add '{ LSHandlerContentType = "public.avi"; LSHandlerRoleAll = "com.apple.quicktimeplayer"; }'
$defaults write "${USERPREFS_DIR}/com.apple.LaunchServices" LSHandlers -array-add '{ LSHandlerContentType = "public.mpeg-4"; LSHandlerRoleAll = "com.apple.quicktimeplayer"; }'

# Set language and region
$defaults write "${USERPREFS_DIR}/.GlobalPreferences" AppleLanguages -array-add 'en_AU' 
$defaults write "${USERPREFS_DIR}/.GlobalPreferences" AppleCollationOrder -string 'en'
$defaults write "${USERPREFS_DIR}/.GlobalPreferences" NSPreferredSpellServerLanguage -string 'en_AU'
$defaults write "${USERPREFS_DIR}/.GlobalPreferences" AppleMeasurementUnits -string 'Centimeters'
$defaults write "${USERPREFS_DIR}/.GlobalPreferences" AppleMetricUnits -boolean true

$defaults write "${USERPREFS_DIR}/com.apple.HIToolbox" AppleDateResID -dict smRoman -int 15
$defaults write "${USERPREFS_DIR}/com.apple.HIToolbox" AppleNumberResID -dict smRoman -int 15
$defaults write "${USERPREFS_DIR}/com.apple.HIToolbox" AppleTimeResID -dict smRoman -int 15
$defaults write "${USERPREFS_DIR}/.GlobalPreferences" AppleLocale -string 'en_AU'

# System Preferences > Software Update > Download updates automatically: off
$defaults write "${PREFS_DIR}/com.apple.SoftwareUpdate" ScheduleFrequency -int -1
$defaults write "${PREFS_DIR}/com.apple.SoftwareUpdate" AutomaticDownload -boolean false

# System Preferences > CDs & DVDs > ignore everything when inserted
$defaults write "${USERPREFS_DIR}/com.apple.digihub" 'com.apple.digihub.cd.music.appeared' '<dict><key>action</key><integer>1</integer></dict>'
$defaults write "${USERPREFS_DIR}/com.apple.digihub" 'com.apple.digihub.cd.picture.appeared' '<dict><key>action</key><integer>1</integer></dict>'
$defaults write "${USERPREFS_DIR}/com.apple.digihub" 'com.apple.digihub.dvd.video.appeared' '<dict><key>action</key><integer>1</integer></dict>'

# Disable the Ping sidebar in iTunes
$defaults write "${USERPREFS_DIR}/com.apple.iTunes" disablePingSidebar -boolean true

# Disable all the other Ping stuff in iTunes
$defaults write "${USERPREFS_DIR}/com.apple.iTunes" disablePing -boolean true

## Magnification on, size in pixels
$defaults write "${USERPREFS_DIR}/com.apple.dock" magnification -boolean true
$defaults write "${USERPREFS_DIR}/com.apple.dock" largesize -int 95

## Autohiding
$defaults write "${USERPREFS_DIR}/com.apple.dock" autohide -boolean true

## Position on screen
$defaults write "${USERPREFS_DIR}/com.apple.dock" orientation -string 'bottom'

# Set Apple Mouse button 1 to Primary click and button 2 to Secondary click.
$defaults write "${USERPREFS_DIR}/com.apple.driver.AppleHIDMouse" Button1 -integer 1
$defaults write "${USERPREFS_DIR}/com.apple.driver.AppleHIDMouse" Button2 -integer 2

# Set Apple Magic Mouse button 1 to Primary click and button 2 to Secondary click.
$defaults write "${USERPREFS_DIR}/com.apple.driver.AppleBluetoothMultitouch.mouse" MouseButtonMode -string 'TwoButton'

# Set Apple Magic Mouse inertia scroll mode 
$defaults write "${USERPREFS_DIR}/com.apple.driver.AppleBluetoothMultitouch.mouse" MouseMomentumScroll -boolean true

# Set Finder Preferences: show all media & servers, arranged by "kind"
# Note: not sure these work - also set by Local MCX
$defaults write "${USERPREFS_DIR}/com.apple.finder" ShowMountedServersOnDesktop -boolean true
$defaults write "${USERPREFS_DIR}/com.apple.finder" ShowRemovableMediaOnDesktop -boolean true
$defaults write "${USERPREFS_DIR}/com.apple.finder" ShowExternalHardDrivesOnDesktop -boolean true
$defaults write "${USERPREFS_DIR}/com.apple.finder" ShowHardDrivesOnDesktop -boolean true
$PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy kind" "${USERPREFS_DIR}/com.apple.finder.plist"
 
# Set Finder Sidebar Preferences: Show all sidebar icons except back to my mac & bonjour
# And not certain any of these work
$PlistBuddy -c "Set :networkbrowser:CustomListProperties:com.apple.NetworkBrowser.bonjourEnabled 0" "${USERPREFS_DIR}/com.apple.sidebarlists.plist"
$PlistBuddy -c "Set :networkbrowser:CustomListProperties:com.apple.NetworkBrowser.backToMyMacEnabled 0" "${USERPREFS_DIR}com.apple.sidebarlists.plist"
$PlistBuddy -c "Set :networkbrowser:CustomListProperties:com.apple.NetworkBrowser.connectedEnabled 1" "${USERPREFS_DIR}/com.apple.sidebarlists.plist"
$PlistBuddy -c "Set :systemitems:ShowEjectables 1" "${USERPREFS_DIR}/com.apple.sidebarlists.plist"
$PlistBuddy -c "Set :systemitems:ShowHardDisks 1" "${USERPREFS_DIR}/com.apple.sidebarlists.plist"
$PlistBuddy -c "Set :systemitems:ShowRemovable 1" "${USERPREFS_DIR}/com.apple.sidebarlists.plist"
$PlistBuddy -c "Set :systemitems:ShowServers 1" "${USERPREFS_DIR}/com.apple.sidebarlists.plist"

# Hide iDisk from the sidebar (in case above doesn't work)
$defaults write "${USERPREFS_DIR}/com.apple.finder" RemoveIDiskFromSidebarOnStartup -boolean true

# Always open to Documents folder (not sure if this is enough)
$defaults write "${USERPREFS_DIR}/com.apple.finder" NewWindowTarget -string 'PfDo'

# Configure Finder to use Column View - but may not be working globally in Lion
$defaults write "${USERPREFS_DIR}/com.apple.finder" AlwaysOpenWindowsInColumnView -boolean true
# Alternatively, this may work, but can be inconsistent
$defaults write "${USERPREFS_DIR}/com.apple.Finder" FXPreferredViewStyle clmv

# Configure Finder to show Path and Status Bars
$defaults write "${USERPREFS_DIR}/com.apple.finder" ShowPathbar -boolean true
$defaults write "${USERPREFS_DIR}/com.apple.finder" ShowStatusBar -boolean true

# System Preferences > Dock (these seem to be overwritten by installed dock)
## Size: pixels
$defaults write "${USERPREFS_DIR}/com.apple.dock" tilesize -int 41

## Minimize windows using: Scale effect
$defaults write "${USERPREFS_DIR}/com.apple.dock" mineffect -string 'scale'


# OS Specific settings

case $OS in
10.6)
# Nothing Snow Leopard only at this point
;;
10.7)
# Lion settings

# Disable Resume system-wide
# First doesn't seem to do anything, so trying two other ways
#$defaults write NSGlobalDomain NSQuitAlwaysKeepsWindows -boolean false
$defaults write "${USERPREFS_DIR}/.GlobalPreferences" NSQuitAlwaysKeepsWindows -boolean false
$defaults write "${USERPREFS_DIR}/com.apple.loginwindow" TALLogoutSavesState -boolean false

# Disables natural scrolling movie on first login for Magic Mouse
$defaults write "${USERPREFS_DIR}/com.apple.SetupAssistant" GestureMovieSeen -string 'mouse'

# Disables iCloud pop-up on first login for Macs running 10.7.2 or higher
$defaults write "${USERPREFS_DIR}/com.apple.SetupAssistant" DidSeeCloudSetup -boolean true

# This prevents addition to dock of all new apps such as Mission Control, App Store etc
# Currently managed through MCX for ifss user - but may not be working 100% there, and this does it for all users
$defaults delete "${PREFS_DIR}/com.apple.dockfixup" add-app
# For some reason Launchpad gets added anyway, so remove it
$defaults write "${PREFS_DIR}/com.apple.dockfixup" 'remove-file' '<dict><key>/Applications/Launchpad.app</key><string>no-val</string></dict>'

;;
esac

exit 0
