#!/bin/bash

# from github.com/natewalck/LuggagePackages
# original version causes plist owner to be set to root
# also probs with syntax around user
# (original had: $3/Users/* -- would result in e.g. "//Users/Shared" and Shared user would match conditional
# Changed for statment to get name of user folder instead of path to user folder
# fixed by SM May 2012

for USERDIR in $( ls $3Users )
do
	if [ "${USERDIR}" != "Shared" ]
		then	
			defaults write $3Users/$USERDIR/Library/Preferences/com.apple.SetupAssistant DidSeeCloudSetup -bool TRUE
			sudo chown `ls -l $3Users | grep $USERDIR | awk '{print $3}'` $3Users/$USERDIR/Library/Preferences/com.apple.SetupAssistant.plist
	fi
done