# Author: Stephen Murphy
# Created: March 2012
# Description: Package Celtx 2.9.7 for unattended install

include /usr/local/share/luggage/luggage.make

TITLE=Celtx_2-9-7_Install
PACKAGE_VERSION=1.0
REVERSE_DOMAIN=au.edu.ifss
PAYLOAD=unbz2-applications-Celtx.app