# Author: Stephen Murphy
# Created: May 2012
# Description: Install Flip4Mac preferences for existing and new users
# Disables update checking

include /usr/local/share/luggage/luggage.make
include ../common/userprefs.make

TITLE=prefs_Flip4Mac
REVERSE_DOMAIN=au.edu.ifss
PACKAGE_VERSION=1.0.0
PFILE=net.telestream.wmv.plist
PAYLOAD=\
	pack-user-template-plist-${PFILE}\
	pack-users-ladmin-Preferences-${PFILE}\
	pack-users-ifss-Preferences-${PFILE}




