# Author: Stephen Murphy
# Created: May 2012
# Description: Package aspectRatio free app for unattended install

include /usr/local/share/luggage/luggage.make

TITLE=aspectRatio-1-12_Install
PACKAGE_VERSION=1.0.0
REVERSE_DOMAIN=au.edu.ifss
PAYLOAD=unbz2-applications-aspectRatio.app