# Author: Stephen Murphy
# Created: May 2012
# Description: Package 5DtoRGB free app for unattended install

include /usr/local/share/luggage/luggage.make

TITLE=5DtoRGB-1-5-3b_Install
PACKAGE_VERSION=1.0.0
REVERSE_DOMAIN=au.edu.ifss
PAYLOAD=unbz2-applications-5DtoRGB.app