# Author: Stephen Murphy
# Created: April 2012
# Description: Install StarDeploy launch daemon plist (sets schedule)
#
# Note that the sssd launchd plist has the same name as the preference file, so two packages needed

include /usr/local/share/luggage/luggage.make

TITLE=launchd_StarDeploy
REVERSE_DOMAIN=au.edu.ifss
PACKAGE_VERSION=1.0.0
PAYLOAD=pack-Library-LaunchDaemons-com.stardeploy.sssd.plist

