# Author: Stephen Murphy
# Created: April 2012
# Description: Package App Store version of Pages 09

include /usr/local/share/luggage/luggage.make

TITLE=Pages_09_Install
PACKAGE_VERSION=1.0
REVERSE_DOMAIN=au.edu.ifss
PAYLOAD=unbz2-applications-Pages.app