# Author: Stephen Murphy
# Created: May 2012
# Description: Basic package that just runs a postflight script
#              Used to test a script

include /usr/local/share/luggage/luggage.make

TITLE=testing_postflight
REVERSE_DOMAIN=au.edu.ifss
PAYLOAD=pack-script-postflight
