#!/bin/bash
#

# Testing logic of script to cycle through the users
# based on script from github.com/natewalck/LuggagePackages
# SM May 2012

#USERLIST=`ls $3Users`
#for USERDIR in $USERLIST

OUTFILE=done3.txt

for USERDIR in $( ls $3Users )
do
	if [ "${USERDIR}" != "Shared" ]
		then
			echo $USERDIR > $3Users/$USERDIR/$OUTFILE
			echo $3Users >> $3Users/$USERDIR/$OUTFILE
			echo $3/Users >> $3Users/$USERDIR/$OUTFILE
			echo $3Users/$USERDIR >> $3Users/$USERDIR/$OUTFILE
			echo $3Users/$USERDIR/$OUTFILE >> $3Users/$USERDIR/$OUTFILE
			echo $0 >> $3Users/$USERDIR/$OUTFILE
			echo $1 >> $3Users/$USERDIR/$OUTFILE
			echo $2 >> $3Users/$USERDIR/$OUTFILE
			echo $3 >> $3Users/$USERDIR/$OUTFILE
			echo $4 >> $3Users/$USERDIR/$OUTFILE
			echo `ls -l $3Users | grep $USERDIR | awk '{print $3}'` >> $3Users/$USERDIR/$OUTFILE
			sudo chown `ls -l $3Users | grep $USERDIR | awk '{print $3}'` $3Users/$USERDIR/$OUTFILE
			#rm $3Users/$USERDIR/okaytodelete
	fi
done

# Note that "exit 0" means installer will think script ran successfully, even if there were errors
# exit 0