# Author: Stephen Murphy
# Created: August 2012
# Description: For experimenting with The Luggage packages
#              Not meant to install anything meaningful

include /usr/local/share/luggage/luggage.make

TITLE=testing_TheLuggage
PACKAGE_VERSION=0.0.0-alpha
REVERSE_DOMAIN=au.edu.ifss
PAYLOAD=pack-en-resource-background.jpg\
		pack-en-resource-Welcome.html
