# Author: Stephen Murphy
# Created: April 2012
# Description: Payload free package to run a postflight script
#              Deletes the Auto Login (any user)

include /usr/local/share/luggage/luggage.make

TITLE=prefs_removeAutoLogin
PACKAGE_VERSION=1.0.0
REVERSE_DOMAIN=au.edu.ifss
PAYLOAD=pack-script-postflight
