# Author: Stephen Murphy
# Created: March 2012
# Description: Package iTerm free app for unattended install

include /usr/local/share/luggage/luggage.make

TITLE=iTerm_1_0_0_Install
PACKAGE_VERSION=1.0.0
REVERSE_DOMAIN=au.edu.ifss
PAYLOAD=unbz2-applications-iTerm.app