# Author: Stephen Murphy
# Created: April 2012
# Description: Payload free package to run a postflight script
#              Deletes Apple script files in IFSS Scripts folder

include /usr/local/share/luggage/luggage.make

TITLE=prefs_removeAppleScripts
PACKAGE_VERSION=1.0.0
REVERSE_DOMAIN=au.edu.ifss
PAYLOAD=pack-script-postflight
