# Author: Stephen Murphy
# Created: March 2012
# Description: Package MindNode free app for unattended install

include /usr/local/share/luggage/luggage.make

TITLE=MindNode_1-8-1_Install
PACKAGE_VERSION=1.0.0
REVERSE_DOMAIN=au.edu.ifss
PAYLOAD=unbz2-applications-MindNode.app